### ISSUE TITLE
API Compatibility with @capacitor/push-notifications

### ISSUE THREAD

**Issue by phal0r** [EinfachHans/capacitor-firebase-push#2]
The official plugin exposes 3 additional events (https://github.com/ionic-team/capacitor-plugins/tree/main/push-notifications#addlistenerregistration-). Does your plugin also fire those events or did you remove them from the native side?

**Comment by EinfachHans** [comment]
The `registration` and `registrationError` Events are not needed at the `register()` Function returns an Promise which resolves or rejects. `pushNotificationActionPerformed` isn't available as this Plugin currently doesn't support notification actions

**Comment by phal0r** [comment]
Thanks for the answer. Do you have something like a roadmap or to-do list, how this plugin can be improved from your side or do you have no plans at all?

Notification Actions and better typing (i.e. passed notification objetcs) would make the plugin more usable.

**Comment by EinfachHans** [comment]
I developed this Plugin because i needed silent push messages in a capacitor app and there was no solution.

I made it open source to 1. give other the option too and 2. work on it with other together.

So if you have any requests or stuff of course you can create a feature request but even better would be a PR 😃

**Comment by phal0r** [comment]
Yes, I want to contribute this, but the first step ist to talk to the maintainer to align the necessary changes :-)
